
- hosts: kvm
  sudo: true
  tasks:

  - name: check vm already exists
    shell: "virsh list --all"
    register: is_vm_exists

  - name: Downloading mirantis openstack iso
    get_url: "url={{ mirantis.url }}{{ mirantis.iso }}  dest=/tmp/{{ mirantis.iso }} sha256sum={{ mirantis.sha256sum }}"

  - name: Creating new virtual machine
    shell: |
      virt-install --connect {{ kvm.server }} \
        --virt-type kvm \
        --name {{ fuel.name }} \
        --vcpu {{ fuel.cpu }} \
        --ram {{ fuel.ram }} \
        --disk {{ fuel.disk_location }}/{{ fuel.name }}.qcow2,size={{ fuel.disk_size }} \
        --os-type linux \
        --graphics vnc \
        {% set delimiter=" " -%}{% for nic in fuel.nics -%} --network bridge={{ nic }},mac=RANDOM{{ delimiter }}{%- endfor %} --autostart \
        --cdrom /tmp/{{ mirantis.iso }}
    when: |
      is_vm_exists.stdout.find( "{{ fuel.name }}" ) == -1

  - name: Waiting for new vm to complete initial install
    shell: virsh list --inactive
    register: result
    until: |
      result.stdout.find("{{ fuel.name }}") != -1
    retries: 100
    delay: 10

  - name: Adding addition network device as we dont yet have ssh access
    template: "src=../templates/fuel_ifcfg-eth1.j2 dest=/tmp/ifcfg-eth1"

  - name: Adding addition network device as we dont yet have ssh access
    template: "src=../templates/network.j2 dest=/tmp/network"

  - shell: |
      virt-copy-in -d {{ fuel.name }} /tmp/ifcfg-eth1 /etc/sysconfig/network-scripts
  
  - shell: |
      virt-copy-in -d {{ fuel.name }} /tmp/network /etc/sysconfig

  - name: start vm
    shell: |
      virsh start {{ fuel.name }}

