
- hosts: kvm
  sudo: true
  tasks:

  - name: check vm already exists
    shell: "virsh list --all"
    register: is_vm_exists

  - name: Getting mirantis openstack iso
    get_url: "url={{ mirantis.url }}{{ mirantis.iso }}  dest=/tmp/{{ mirantis.iso }} sha256sum={{ mirantis.sha256sum }}"

  - name: Create virtual machine
    shell: |
      virt-install --connect {{ kvm.server }} \
        --virt-type kvm \
        --name {{ fuel.name }} \
        --vcpu {{ fuel.cpu }} \
        --ram {{ fuel.ram }} \
        --disk {{ fuel.disk_location }}/{{ fuel.name }}.qcow2,size={{ fuel.disk_size }} \
        --os-type linux \
        --graphics vnc \
        {% for nic in fuel.nics -%} --network bridge={{ nic }},mac=RANDOM{%- endfor %} \
        --autostart \
        --cdrom /tmp/{{ mirantis.iso }}
    when: |
      not is_vm_exists.stdout.find( "{{ fuel.name }}" )

  - name: Wait until vm stops
    shell: virsh list --inactive
    register: result
    until: |
      result.stdout.find("{{ fuel.name }}")
    retries: 12
    delay: 5
  
  - name: make sure guestmount is installed
    sudo: true
    yum: name=libguestfs-tools state=latest

  - name: create mount directory 
    file: |
      path=/mnt/"{{ fuel.name }}" state=directory
  
  - stat: "path=/mnt/{{ fuel.name }}/etc/"
    register: is_mounted

  - name: mount qcow2 image
    shell: |
      guestmount -d "{{ fuel.name }}" -i /mnt/"{{ fuel.name }}"
    when: is_mounted.stat.exists == False

  - name: add new network device
    template: "src=../templates/fuel_ifcfg-eth1.j2 dest=/mnt/{{ fuel.name }}/etc/sysconfig/network-scripts/ifcfg-eth1"

  - name: unmount vm
    shell: "umount /mnt/{{ fuel.name }}"

  - name: start vm
    shell: virsh start "{{ fuel.name }}"

